name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Set up MongoDB
        uses: mongo/setup-mongodb@v0
        with:
          mongodb-version: 'latest'

      - name: Run MongoDB
        run: |
          mongod --fork --logpath /tmp/mongod.log --logappend
          sleep 5

      - name: Run Spring Boot App
        run: |
          java -jar target/your-spring-boot-app.jar
